[global]
showWarningOnDirectExecution = false

[client]
showErrorDetails = false

[theme]
base="light"
primaryColor="#EF0A83"

[server]
port = 9501
enableCORS = false
enableXsrfProtection=false
maxUploadSize = 25
enableWebsocketCompression = false
